env:
  global:
    - CONAN_USERNAME: "artem-kamyshev"
    - CONAN_LOGIN_USERNAME: "artem-kamyshev"
    - CONAN_CHANNEL: "ci"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/artem-kamyshev/conan-test"
    - CONAN_REMOTES: "https://api.bintray.com/conan/artem-kamyshev/conan-test, https://api.bintray.com/conan/conan/conan-center"

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker
matrix:
  include:
    - <<: *linux
      env: CONAN_REFERENCE=openssl/1.1.1d CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release
      install:
        - chmod +x ./recipes/openssl/ALL/.travis/install.sh
        - ./recipes/openssl/ALL/.travis/install.sh
      script:
        - chmod +x ./recipes/openssl/ALL/.travis/run.sh
        - ./recipes/openssl/ALL/.travis/run.sh
    - <<: *linux
      env: CONAN_REFERENCE=zlib/1.2.11 CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=conanio/gcc48 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release
      install:
        - chmod +x ./recipes/zlib/1.2.11/.travis/install.sh
        - ./recipes/zlib/1.2.11/.travis/install.sh
      script:
        - chmod +x ./recipes/zlib/1.2.11/.travis/run.sh
        - ./recipes/zlib/1.2.11/.travis/run.sh
                  
