name: zlib CI

on:
  pull_request:
    paths:
      - 'recipes/zlib/1.2.11/**'
      - 'build.py'
      - '.github/workflows/zlib.yml'
  push:
    branches:
      - test_ci
    paths:
      - 'recipes/zlib/1.2.11/**'
      - 'build.py'
      - '.github/workflows/zlib.yml'

env:
  CONAN_USERNAME: 'artem-kamyshev'
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_STABLE_CHANNEL: 'stable'
  CONAN_UPLOAD: 'https://api.bintray.com/conan/artem-kamyshev/conan-test'
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  CONAN_STABLE_BRANCH_PATTERN: 'test_ci'
  CONAN_REMOTES: 'https://api.bintray.com/conan/artem-kamyshev/conan-test'
  CONAN_BUILD_TYPES: 'Release,Debug'
  CONAN_REFERENCE: 'zlib/1.2.11'
  CONAN_ARCHS: 'x86, x86_64'

jobs:
  zlib_1_2_11:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        include:
          - os: "ubuntu-latest"
            gcc_version: '4.8'
            docker_image: 'conanio/gcc48'
            install_py3venv: 'sudo apt-get install python3-venv && python3 -m venv conan_env'
          - os: "macos-latest"
            xcode_version: '11.3.1'
            clang_version: '9.0.1'
            install_py3venv: 'pyvenv conan_env'

    runs-on: ${{ matrix.os }}
    env:
      CONAN_GCC_VERSIONS: ${{ matrix.gcc_version }}
      CONAN_DOCKER_IMAGE: ${{ matrix.docker_image }}
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
      CONAN_APPLE_CLANG_VERSIONS: ${{ matrix.clang_version }}
    steps:
      - name: Install conan
        # if you add support for gcc >= 5 then add creation of a new conan profile and
        # setup of compiler.libcxx=libstdc++11 for such builds while maintaning old ABI for others
        run: |
          mkdir conan_env
          ${{ matrix.install_py3venv }}
          source conan_env/bin/activate
          pip install pip --upgrade
          pip install setuptools --upgrade
          pip install conan --upgrade
          pip install conan_package_tools --upgrade
          conan user
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'sources'
      - name: Build job
        run: |
          source conan_env/bin/activate
          cd sources/recipes/zlib/1.2.11
          python ../../../build.py
        shell: bash