name: zlib CI

on:
  pull_request:
    paths: 'recipes/zlib/1.2.11/**'

env:
  CONAN_USERNAME: "artem-kamyshev"
  CONAN_LOGIN_USERNAME: "artem-kamyshev"
  CONAN_CHANNEL: "ci"
  CONAN_UPLOAD: "https://api.bintray.com/conan/artem-kamyshev/conan-test"
  CONAN_REMOTES: "https://api.bintray.com/conan/artem-kamyshev/conan-test"
  CONAN_BUILD_TYPES: 'Release,Debug'
  CONAN_REFERENCE: 'zlib/1.2.11'
  CONAN_GCC_VERSIONS: 4.8
  CONAN_DOCKER_IMAGE: 'conanio/gcc48'
  CONAN_ARCHS: 'x86_64'

jobs:
  zlib_1_2_11:
    runs-on: ubuntu-latest
    steps:
      - name: Install conan
        run: |
          mkdir conan_env
          python3 -m venv conan_env
          source conan_env/bin/activate
          pip install conan --upgrade
          pip install conan_package_tools --updgrade
          conan user
        shell: bash
      - name: Build job
        run: cd recipes/zlib/1.2.11 && ../../../build.py
        shell: bash
          
